from pathlib import Path
import json
import datetime as dt
import pandas as pd

class RegimePlaybookGenerator:
    def __init__(self, data_dir: Path, summary_path: Path):
        self.data_dir = data_dir
        self.summary_path = summary_path

    def _detect_current_regime(self, labeled_fname: str) -> str:
        path = self.data_dir / labeled_fname
        if not path.exists():
            return "UNKNOWN"
            
        df = pd.read_csv(path, parse_dates=["timestamp"])
        df = df.sort_values("timestamp")
        if df.empty:
            return "UNKNOWN"
            
        last_row = df.iloc[-1]
        return last_row["state"] # 'state' column from label_20y_regimes.py

    def _load_summary(self) -> dict:
        if not self.summary_path.exists():
            return {}
            
        with open(self.summary_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def generate_markdown(self, labeled_fname: str, out_dir: Path):
        today = dt.date.today().isoformat()
        regime = self._detect_current_regime(labeled_fname)
        summary = self._load_summary()
        info = summary.get(regime, {})
        
        hist_stats = info.get("historical_stats", {})

        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"regime_playbook_{today}.md"

        with open(out_path, "w", encoding="utf-8") as f:
            f.write(f"# Regime Playbook – {today} (KR)\n\n")
            
            # 1. Current Status
            f.write(f"## 1. Market Status\n")
            f.write(f"- **Current Regime**: **{regime}**\n")
            if regime == "GREEN":
                f.write("- **Description**: Bull Market (Rising Trend, Low Volatility)\n")
            elif regime == "YELLOW":
                f.write("- **Description**: Choppy/Sideways (Uncertain Trend)\n")
            elif regime == "RED":
                f.write("- **Description**: Bear Market (Falling Trend, High Volatility)\n")
            f.write("\n")

            # 2. Strategy Recommendation
            f.write(f"## 2. Strategy Recommendation\n")
            if info:
                strategy = info.get('strategy', 'N/A')
                params = info.get('params', {})
                f.write(f"- **Recommended Strategy**: `{strategy}`\n")
                f.write(f"- **Parameters**: {params}\n")
                
                if hist_stats:
                    f.write(f"- **Historical Performance ({regime})**:\n")
                    f.write(f"  - **Sharpe Ratio**: {hist_stats.get('sharpe', 'N/A')}\n")
                    f.write(f"  - **CAGR (Approx)**: {hist_stats.get('cagr', 'N/A'):.2%}\n")
                    f.write(f"  - **Max Drawdown**: {hist_stats.get('max_dd', 'N/A'):.2%}\n")
                    f.write(f"  - **Win Rate**: {hist_stats.get('win_rate', 'N/A'):.2%}\n")
            else:
                f.write("- No strategy recommendation available for this regime.\n")
            f.write("\n")

            # 3. Operational Guide (Template)
            f.write(f"## 3. Operational Guide\n")
            
            if regime == "GREEN":
                f.write("### Position Sizing\n")
                f.write("- **Base Risk**: 1.0R (Aggressive)\n")
                f.write("- **Max Trades**: Unlimited (as long as trend holds)\n")
                f.write("\n### Entry Rules\n")
                f.write("- Buy on pullbacks to fast MA.\n")
                f.write("- Pyramid on strength.\n")
                
            elif regime == "YELLOW":
                f.write("### Position Sizing\n")
                f.write("- **Base Risk**: 0.5R (Conservative)\n")
                f.write("- **Max Trades**: 3 per day\n")
                f.write("\n### Entry Rules\n")
                f.write("- Wait for confirmation candles.\n")
                f.write("- Take quick profits (don't hold for home runs).\n")

            elif regime == "RED":
                f.write("### Position Sizing\n")
                f.write("- **Base Risk**: 0.3R (Defensive)\n")
                f.write("- **Max Trades**: 1-2 per day (Sniper mode)\n")
                f.write("\n### Entry Rules\n")
                f.write("- Mean Reversion only (buy extreme fear).\n")
                f.write("- Strict stop losses.\n")
                f.write("- **Cash is a position**.\n")
            
            else:
                f.write("- Stay in Cash.\n")

            f.write("\n---\n")
            f.write(f"*Generated by Garam Regime Engine on {dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
            
        print(f"Generated Daily Playbook: {out_path}")
