
import pandas as pd
import os

class UnifiedDataLoader:
    """
    Central Access Point for Unified Wide-Format Data (Phase 31).
    Reads Parquet/CSV generated by `scripts/build_wide_history.py`.
    """
    
    DEFAULT_PATH = "GARAM_Data/unified"
    
    def __init__(self, data_dir=None):
        self.data_dir = data_dir or self.DEFAULT_PATH
        
    def load_wide_close(self):
        """Load Wide-Format Close Prices (Index=Time, Col=Symbol)."""
        path = os.path.join(self.data_dir, "wide_close.parquet")
        if not os.path.exists(path):
            raise FileNotFoundError(f"Unified Close Data not found at {path}. Run scripts/build_wide_history.py first.")
        return pd.read_parquet(path)
    
    def load_wide_volume(self):
        """Load Wide-Format Volume (Index=Time, Col=Symbol)."""
        path = os.path.join(self.data_dir, "wide_volume.parquet")
        if not os.path.exists(path):
            raise FileNotFoundError(f"Unified Volume Data not found at {path}.")
        return pd.read_parquet(path)
        
    def get_universe(self):
        """Get list of symbols from the dataset columns."""
        df = self.load_wide_close()
        return list(df.columns)
        
    def load_aligned_data(self):
        """Returns (close_df, vol_df) guaranteed to be aligned."""
        close = self.load_wide_close()
        vol = self.load_wide_volume()
        
        # Intersection of index/columns to ensure safety
        common_idx = close.index.intersection(vol.index)
        common_col = close.columns.intersection(vol.columns)
        
        return close.loc[common_idx, common_col], vol.loc[common_idx, common_col]

# Singleton/Convenience
loader = UnifiedDataLoader()
