# garam_core/research/pulse/label_gen.py
import pandas as pd

def generate_labels(df: pd.DataFrame, n_out: int = 5, threshold: float = 0.001) -> pd.DataFrame:
    """
    Generates target labels based on future return over n_out bars.
    Label = +1 if ret > threshold
    Label = -1 if ret < -threshold
    Label = 0 otherwise
    """
    df = df.copy()
    
    # Future return: (Close[t+n] / Close[t]) - 1
    future_ret = df["close"].shift(-n_out) / df["close"] - 1
    
    df["label"] = 0
    df.loc[future_ret > threshold, "label"] = 1
    df.loc[future_ret < -threshold, "label"] = -1
    
    # Drop/fill NaNs generated by shift
    # Or just leave 0 for last bars
    
    return df
