import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import sys

# Setup Paths
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(project_root))

def load_trade_log(path, label, color):
    # Simulates equity curve from trade log
    if not path.exists():
        print(f"File not found: {path} (Skipping {label})")
        return None
    
    df = pd.read_csv(path)
    df['time'] = pd.to_datetime(df['time'])
    df = df.sort_values('time')
    
    capital = 10_000_000.0
    equity_curve = []
    
    # Needs to handle daily gaps? 
    # Just plotting realized PnL change points + final balance
    # But better to reconstruct daily equity?
    # For now, just plot balance snapshots after each trade
    
    current_bal = capital
    equity_curve.append({"time": df['time'].iloc[0], "equity": capital}) # Start
    
    for _, row in df.iterrows():
        # Update balance only on realized (But audit log has 'balance' column)
        # If the log has 'balance' column, use it directly?
        # But balance is cash. Equity = Cash + Unrealized.
        # This script plots Realized Equity (Balance after trade).
        # v1 and v1.1 scripts saves 'balance' after each trade.
        # v0 script also has balance.
        
        # In BUY, balance becomes 0 (all cash -> stock).
        # In SELL, balance becomes Total Equity.
        # So we should only plot SELL rows to see Equity curve (Realized).
        
        if row['side'] == 'SELL':
            equity_curve.append({"time": row['time'], "equity": row['balance']})
            
    df_eq = pd.DataFrame(equity_curve)
    df_eq['label'] = label
    df_eq['color'] = color
    return df_eq

def run_viz():
    # Paths
    p_v0 = project_root / "results" / "audit" / "trades_week1.csv" # Actually generated by audit v1? Or audit v2?
    # Audit v2 generates `trades_week1_cost10.csv`
    p_v0 = project_root / "results" / "audit" / "week1_v2" / "trades_week1_cost10.csv"
    
    p_v1 = project_root / "results" / "simulation" / "week1_v1" / "trades_week1_policy_v1.csv"
    p_v1_1 = project_root / "results" / "simulation" / "week1_v1_1" / "trades_week1_policy_v1_1.csv"
    
    curves = []
    
    c0 = load_trade_log(p_v0, "Policy v0 (Baseline)", "gray")
    if c0 is not None: curves.append(c0)
        
    c1 = load_trade_log(p_v1, "Policy v1 (Naive Mining)", "blue")
    if c1 is not None: curves.append(c1)
        
    c1_1 = load_trade_log(p_v1_1, "Policy v1.1 (Optimized)", "red")
    if c1_1 is not None: curves.append(c1_1)
    
    # Plot
    plt.figure(figsize=(12, 6))
    
    for c in curves:
        # Normalize to % Return
        c['return'] = (c['equity'] / 10_000_000.0) - 1.0
        plt.plot(c['time'], c['return']*100, label=f"{c['label'].iloc[0]} ({c['return'].iloc[-1]*100:.2f}%)", 
                 color=c['color'].iloc[0], marker='o', markersize=4)
        
    plt.title("Week-1 Policy Comparison (Simulation)")
    plt.ylabel("Return (%)")
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend()
    plt.axhline(0, color='black', linewidth=1)
    
    out_path = project_root / "results" / "simulation" / "week1_policy_comparison.png"
    plt.savefig(out_path)
    print(f"Saved Chart: {out_path}")

if __name__ == "__main__":
    run_viz()
