import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from pathlib import Path

# Title
st.title("400 Symbol Edge Map Dashboard")

# Check Data
if not Path("edge_map_overall_400.csv").exists():
    st.error("CSV 'edge_map_overall_400.csv' not found. Run pipeline first.")
    st.stop()

# Load data
df_overall = pd.read_csv("edge_map_overall_400.csv")
if Path("edge_map_by_regime_400.csv").exists():
    df_regime = pd.read_csv("edge_map_by_regime_400.csv")
else:
    df_regime = pd.DataFrame()

# Sidebar filters
with st.sidebar:
    st.header("Filters")
    if not df_regime.empty:
        regime_select = st.multiselect(
            "Regime Selection",
            options=df_regime["regime"].unique(),
            default=df_regime["regime"].unique()
        )
    else:
        regime_select = []
    
    min_trades = st.slider("Min trades overall", 0, 200, 10)

# Filter
df_overall_filtered = df_overall[df_overall["trades"] >= min_trades]
if not df_regime.empty:
    df_regime_filtered = df_regime[df_regime["regime"].isin(regime_select)]
else:
    df_regime_filtered = pd.DataFrame()

# Overall Net Expectancy Distribution
st.subheader("Overall Net Expectancy Distribution")
fig1 = px.histogram(df_overall_filtered, x="net_expectancy", nbins=50, title="Net Expectancy")
st.plotly_chart(fig1)

# Cost vs Net Expectancy
st.subheader("Cost vs Net Expectancy Scatter")
fig2 = px.scatter(
    df_overall_filtered,
    x="cost_avg", y="net_expectancy",
    color="win_rate", hover_data=["symbol"],
    title="Cost Impact"
)
st.plotly_chart(fig2)

# Regime Net Expectancy
if not df_regime_filtered.empty:
    st.subheader("Net Expectancy by Regime")
    fig3 = px.box(
        df_regime_filtered, x="regime",
        y="net_expectancy",
        points="all",
        color="regime",
        title="Regime Performance"
    )
    st.plotly_chart(fig3)

# Trades per Day
st.subheader("Trades per Day Distribution")
fig4 = px.histogram(df_overall_filtered, x="trades_per_day", nbins=40, title="Trades Freq")
st.plotly_chart(fig4)

st.write("Generated by GARAM Edge Map Pipeline")
