# scripts/sync_universe.py
from __future__ import annotations

import sys
from pathlib import Path

# Add project root to sys.path
sys.path.append(str(Path(__file__).resolve().parents[1]))

from garam_core.health.gate import gate_environment

def main():
    print(">>> Syncing Universe from History...")
    
    # Resolve Paths
    project_root = Path("c:/garam/garam/garam_core")
    paths = gate_environment(project_root)
    
    history_dir = paths.data_root / "history" / "minute"
    if not history_dir.exists():
        print(f"[ERROR] History dir not found: {history_dir}")
        return

    # Scan
    files = list(history_dir.glob("*.csv"))
    symbols = sorted([f.stem for f in files])
    print(f"Found {len(symbols)} symbols in history.")
    
    # Write YAML
    out_path = project_root / "config" / "universe_kr_top50.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Generated by scripts/sync_universe.py\n")
        f.write("# Snapshot of available minute data\n")
        for s in symbols:
            f.write(f"- '{s}'\n")
            
    print(f"Written universe to {out_path}")

if __name__ == "__main__":
    main()
